package com.kunal.project_management_system.entity;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "tasks")
public class Task {

    // =====================================================
    // TASK ID
    // =====================================================

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "task_id")
    private Integer taskId;


    // =====================================================
    // REQUIREMENT
    // =====================================================

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(
            name = "requirement_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_task_requirement")
    )
    private Requirement requirement;


    // =====================================================
    // REQUIREMENT ID
    // Used to receive requirementId from React
    // =====================================================

    @Transient
    private Integer requirementId;


    // =====================================================
    // TASK TITLE
    // =====================================================

    @Column(
            name = "task_title",
            nullable = false,
            length = 200
    )
    private String taskTitle;


    // =====================================================
    // TASK DESCRIPTION
    // =====================================================

    @Column(
            name = "task_description",
            columnDefinition = "TEXT"
    )
    private String taskDescription;


    // =====================================================
    // TASK PRIORITY
    // =====================================================

    @Enumerated(EnumType.STRING)
    @Column(
            name = "task_priority",
            nullable = false
    )
    private TaskPriority taskPriority;


    // =====================================================
    // TASK STATUS
    // =====================================================

    @Enumerated(EnumType.STRING)
    @Column(
            name = "task_status",
            nullable = false
    )
    private TaskStatus taskStatus;


    // =====================================================
    // ASSIGNED TO
    // =====================================================

    @Column(
            name = "task_assigned_to",
            length = 150
    )
    private String taskAssignedTo;


    // =====================================================
    // TASK START DATE
    // Automatically generated by backend
    // =====================================================

    @Column(name = "task_start_date")
    private LocalDateTime taskStartDate;


    // =====================================================
    // TASK DUE DATE
    // Optional
    // =====================================================

    @Column(name = "task_due_date")
    private LocalDate taskDueDate;


    // =====================================================
    // TASK COMPLETED DATE
    // Optional
    // =====================================================

    @Column(name = "task_completed_date")
    private LocalDate taskCompletedDate;


    // =====================================================
    // DEFAULT CONSTRUCTOR
    // =====================================================

    public Task() {
    }


    // =====================================================
    // GET TASK ID
    // =====================================================

    public Integer getTaskId() {
        return taskId;
    }


    // =====================================================
    // SET TASK ID
    // =====================================================

    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }


    // =====================================================
    // GET REQUIREMENT
    // =====================================================

    public Requirement getRequirement() {
        return requirement;
    }


    // =====================================================
    // SET REQUIREMENT
    // =====================================================

    public void setRequirement(Requirement requirement) {
        this.requirement = requirement;
    }


    // =====================================================
    // GET REQUIREMENT ID
    // =====================================================

    public Integer getRequirementId() {
        return requirementId;
    }


    // =====================================================
    // SET REQUIREMENT ID
    // =====================================================

    public void setRequirementId(Integer requirementId) {
        this.requirementId = requirementId;
    }


    // =====================================================
    // GET TASK TITLE
    // =====================================================

    public String getTaskTitle() {
        return taskTitle;
    }


    // =====================================================
    // SET TASK TITLE
    // =====================================================

    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }


    // =====================================================
    // GET TASK DESCRIPTION
    // =====================================================

    public String getTaskDescription() {
        return taskDescription;
    }


    // =====================================================
    // SET TASK DESCRIPTION
    // =====================================================

    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }


    // =====================================================
    // GET TASK PRIORITY
    // =====================================================

    public TaskPriority getTaskPriority() {
        return taskPriority;
    }


    // =====================================================
    // SET TASK PRIORITY
    // =====================================================

    public void setTaskPriority(TaskPriority taskPriority) {
        this.taskPriority = taskPriority;
    }


    // =====================================================
    // GET TASK STATUS
    // =====================================================

    public TaskStatus getTaskStatus() {
        return taskStatus;
    }


    // =====================================================
    // SET TASK STATUS
    // =====================================================

    public void setTaskStatus(TaskStatus taskStatus) {
        this.taskStatus = taskStatus;
    }


    // =====================================================
    // GET ASSIGNED TO
    // =====================================================

    public String getTaskAssignedTo() {
        return taskAssignedTo;
    }


    // =====================================================
    // SET ASSIGNED TO
    // =====================================================

    public void setTaskAssignedTo(String taskAssignedTo) {
        this.taskAssignedTo = taskAssignedTo;
    }


    // =====================================================
    // GET START DATE
    // =====================================================

    public LocalDateTime getTaskStartDate() {
        return taskStartDate;
    }


    // =====================================================
    // SET START DATE
    // =====================================================

    public void setTaskStartDate(LocalDateTime taskStartDate) {
        this.taskStartDate = taskStartDate;
    }


    // =====================================================
    // GET DUE DATE
    // =====================================================

    public LocalDate getTaskDueDate() {
        return taskDueDate;
    }


    // =====================================================
    // SET DUE DATE
    // =====================================================

    public void setTaskDueDate(LocalDate taskDueDate) {
        this.taskDueDate = taskDueDate;
    }


    // =====================================================
    // GET COMPLETED DATE
    // =====================================================

    public LocalDate getTaskCompletedDate() {
        return taskCompletedDate;
    }


    // =====================================================
    // SET COMPLETED DATE
    // =====================================================

    public void setTaskCompletedDate(LocalDate taskCompletedDate) {
        this.taskCompletedDate = taskCompletedDate;
    }
}